### ISSUE TITLE
Add reverse mapping - JSON to GraphQL schema type def

### ISSUE THREAD

**Issue by kristianmandrup** [jjwtay/graphSchemaToJson#1]
Any chance you could take the JSON and re-generate the GraphQL type defs as a formatted string?
Perhaps could go in a separate library?

Also, could you please document the output format or show an example output in the `Readme`.
Thanks.

**Comment by kristianmandrup** [comment]
Made a [PR](https://github.com/jjwtay/graphSchemaToJson/pull/2) with better docs and run example

**Comment by jjwtay** [comment]
merged
